- hosts: localhost
  vars_files:
    - ~/.setup_vars.yml
  become_user: "{{ user }}"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      become: true
      become_user: root
  tasks:
    - name: Include installation tasks
      include_tasks: tasks/install_packages.yml

    - name: Include configuration tasks
      include_tasks: tasks/configurations.yml
