- hosts: localhost
  become_user: ronualdomaciel
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      become: true
      become_user: root
  tasks:
    - include: tasks/install_packages.yml
