- name: Creates workspace folder
  file:
    name: "{{ workspace_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"

- name: Retrieving configuration
  git:
    repo: https://github.com/ronualdo/dotfiles.git
    dest: "{{ workspace_folder }}/dotfiles"

- name: Sets up git
  file:
    src: "{{ workspace_folder }}/dotfiles/.gitconfig"
    dest: "/home/{{ user }}/.gitconfig"
    state: link
    owner: "{{ user }}"
    force: true

- name: Checks current nvim config
  stat: path="/home/{{ user }}/.config/nvim"
  register: nvim_config

- name: Remove default nvim config
  file:
    path: "/home/{{ user }}/.config/nvim"
    state: absent
  when: nvim_config.stat.isdir is defined and nvim_config.stat.isdir

- name: Sets up nvim config
  file:
    src: "{{ workspace_folder }}/dotfiles/nvim/"
    dest: "/home/{{ user }}/.config/nvim"
    state: link
    owner: "{{ user }}"
    force: true

- name: Install nvim plugins
  command: nvim --headless +PlugInstall +qa

- name: Sets up tmux
  file:
    src: "{{ workspace_folder }}/dotfiles/.tmux.conf"
    dest: "/home/{{ user }}/.tmux.conf"
    state: link
    owner: "{{ user }}"
    force: true

- name: Sets up zshrc
  file:
    src: "{{ workspace_folder }}/dotfiles/.zshrc"
    dest: "/home/{{ user }}/.zshrc"
    state: link
    owner: "{{ user }}"
    force: true

- name: Sets up zshrc functions
  file:
    src: "{{ workspace_folder }}/dotfiles/functions"
    dest: "/home/{{ user }}/functions"
    state: link
    owner: "{{ user }}"
    force: true

- name: Sets up zsh custom
  file:
    src: "{{ workspace_folder }}/dotfiles/zsh_custom"
    dest: "/home/{{ user }}/zsh_custom"
    state: link
    owner: "{{ user }}"
    force: true

- name: Sets up ohmyzsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ user }}/zsh_custom/plugins/zsh-autosuggestions"

- name: Sets up ohmyzsh syntax highlight
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user }}/zsh_custom/plugins/zsh-syntax-highlighting"

- name: Sets up shell for user
  become: yes
  become_user: root
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Adds user to docker group
  become: yes
  become_user: root
  user:
    name: "{{ user }}"
    append: yes
    groups: 'docker'

- name: Sets dock fixed
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
    value: "false"

# Not sure if needed
# - sysctl:
#     name: fs.inotify.max_user_watches
#     value: '1048576'
#   become: yes
#   become_user: root
# 
# - sysctl:
#     name: vm.max_map_count
#     value: '262144'
#   become: yes
#   become_user: root
