- name: Adds neovim ppa repository
  become: true
  become_user: root
  apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Adds telegram ppa repository
  become: true
  become_user: root
  apt_repository:
    repo: ppa:atareao/telegram

- name: Adds docker ppa key
  become: true
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Adds docker ppa repository
  become: true
  become_user: root
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Adds linux uprising repository (Java)
  become: true
  become_user: root
  apt_repository:
    repo: ppa:linuxuprising/java

- name: Adds rabbitmq repository for erlang
  become: true
  become_user: root
  apt_repository:
    repo: ppa:rabbitmq/rabbitmq-erlang 

# change to install using nvm
- name: Check nodejs is present
  command: nodejs --version
  ignore_errors: yes
  register: result

- name: Install nodejs PPA
  become: true
  become_user: root
  shell: curl -sL https://deb.nodesource.com/setup_18.x | bash -s -- y
  when: result is failed

- name: Install docker-compose
  become: true
  become_user: root
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '555'

- name: Install packages
  become: true
  become_user: root
  apt:
    name: 
      - git
      - zsh
      - neovim
      - tmux
      - tmate
      - telegram
      - fonts-hack-ttf
      - ripgrep
      - elixir
      - erlang-dev
      - erlang-xmerl
      - build-essential
      - python-dev
      - python3-dev
      - python3-pip
      - postgresql-client
      - dconf-cli
      - net-tools
      - software-properties-common
      - httpie
      # - fzf removing cause it is not available on apt repo for ubuntu 18.04
      # rbenv dependencies
      - autoconf
      - bison 
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - docker-ce
      - libpq-dev


- name: Install rbenv
  git:
   repo: https://github.com/rbenv/rbenv.git
   dest: ~/.rbenv

- name: Install ruby-builds (rbenv dep)
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install rbenv-default-gems (set it up to automatically install bundler)
  git:
    repo: https://github.com/rbenv/rbenv-default-gems.git
    dest: ~/.rbenv/plugins/rbenv-default-gems


- name: Check neovim-remote is present
  command: pip3 show neovim-remote
  ignore_errors: yes
  register: result

- name: Install neovim-remote
  command: pip3 install neovim-remote
  when: result is failed

- name: Check psutil is present
  command: pip3 show psutil 
  ignore_errors: yes
  register: result

- name: Install psutil (ansible dconf module dep)
  command: python -m pip install psutil
  when: result is failed

- name: Check mspack is present
  command: pip3 show msgpack
  ignore_errors: yes
  register: result

- name: Install msgpack (deoplete dependency)
  command: pip3 install msgpack
  when: result is failed

- name: Install docker-compose
  become: true
  become_user: root
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '555'

- name: Install ngrok
  become: true
  become_user: root
  unarchive:
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '555'

- name: Create docker group
  become: true
  become_user: root
  group:
    name: docker
    state: present

- name: Create docker user
  become: true
  become_user: root
  user: name=docker group=docker

- name: Check slack is present
  command: slack --version
  ignore_errors: yes
  register: result

- name: Adds slack
  become: true
  become_user: root
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.7.0-amd64.deb
  when: result is failed

- name: Adds dropbox
  become: true
  become_user: root
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb

- name: Adds oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: Adds heroku cli
  become: true
  become_user: root
  snap:
    name: heroku
    classic: true
